theme: minima
title: Romain Tajan
logo: /assets/img/photo.jpg
description: Associate professor
header_pages:
  - teaching.md
  - research.md

plugins_dir: _plugins

markdown: kramdown
parse_block_html: true

scholar:
  style: _plugins/ieee.csl
  source: _bibliography
  bibliography: refs.bib
  sort_by: year,month
  order: ascending
  group_by: type
  group_order: type
  type_order: [article,inproceedings, misc, phdthesis,techreport]
  bibtex_filters:
    - latex
    - markdown
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   '[details]'